import { createRequire } from 'node:module';
const require = createRequire('/opt/node22/lib/node_modules/');
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 640, height: 360 } });
const logs = [];
page.on('console', (m) => logs.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}`));
await page.goto('http://localhost:5173/');
await page.waitForTimeout(1500);
await page.evaluate(() => { const f = window.fountain; f.ui.toggleHidden(); f.stage.mist.enabled = false; document.getElementById('ui').style.display='none'; });
await page.waitForTimeout(8000);
await page.screenshot({ path: '/tmp/claude-0/shots/rd-0.png' });
const info = await page.evaluate(() => {
  const st = window.fountain.stage;
  const m = st.particles.mesh;
  const u = m.material.uniforms;
  u.uBright.value = 50;
  return { simTime: st.simTime, visible: m.visible, instanceCount: m.geometry.instanceCount, bright: u.uBright.value, res: [u.uRes.value.x, u.uRes.value.y], camPos: st.camera.position.toArray().map(x=>+x.toFixed(1)), fov: st.camera.fov };
});
console.log(JSON.stringify(info));
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/claude-0/shots/rd-1.png' });
console.log(logs.join('\n'));
await browser.close();
